// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
extern lv_obj_t * ui_ScreenHome;
void ui_event_TabView1(lv_event_t * e);
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_tabhome;
void ui_event_homePumpStatusComponentFloor0_HomePumpStatusComponent(lv_event_t * e);
extern lv_obj_t * ui_homePumpStatusComponentFloor0;
void ui_event_homePumpStatusComponentFloor1_HomePumpStatusComponent(lv_event_t * e);
extern lv_obj_t * ui_homePumpStatusComponentFloor1;
extern lv_obj_t * ui_tabsettings;
extern lv_obj_t * ui_settingsGroundFloor;
void ui_event_settingsGroundFloor_floorTempRoller(lv_event_t * e);
extern lv_obj_t * ui_settingsFloor1;
void ui_event_settingsFloor1_floorTempRoller(lv_event_t * e);
extern lv_obj_t * ui_tabmanual;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
