// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_HOMEPUMPSTATUSCOMPONENT_H
#define _UI_COMP_HOMEPUMPSTATUSCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT HomePumpStatusComponent
#define UI_COMP_HOMEPUMPSTATUSCOMPONENT_HOMEPUMPSTATUSCOMPONENT 0
#define UI_COMP_HOMEPUMPSTATUSCOMPONENT_NAMELABEL 1
#define UI_COMP_HOMEPUMPSTATUSCOMPONENT_TEMPLABEL 2
#define UI_COMP_HOMEPUMPSTATUSCOMPONENT_STATUSBAR 3
#define _UI_COMP_HOMEPUMPSTATUSCOMPONENT_NUM 4
lv_obj_t *ui_HomePumpStatusComponent_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
