// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_FLOORSETTINGSCOMPONENT_H
#define _UI_COMP_FLOORSETTINGSCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT FloorSettingsComponent
#define UI_COMP_FLOORSETTINGSCOMPONENT_FLOORSETTINGSCOMPONENT 0
#define UI_COMP_FLOORSETTINGSCOMPONENT_LABELFLOORTEMP 1
#define UI_COMP_FLOORSETTINGSCOMPONENT_FLOORTEMPROLLER 2
#define _UI_COMP_FLOORSETTINGSCOMPONENT_NUM 3
lv_obj_t * ui_FloorSettingsComponent_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
