// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT FloorSettingsComponent

lv_obj_t * ui_FloorSettingsComponent_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_FloorSettingsComponent;
    cui_FloorSettingsComponent = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_FloorSettingsComponent, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(cui_FloorSettingsComponent, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_FloorSettingsComponent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_FloorSettingsComponent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_FloorSettingsComponent, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_FloorSettingsComponent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_FloorSettingsComponent, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_FloorSettingsComponent, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_FloorSettingsComponent, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_FloorSettingsComponent, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labelFloorTemp;
    cui_labelFloorTemp = lv_label_create(cui_FloorSettingsComponent);
    lv_obj_set_width(cui_labelFloorTemp, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_labelFloorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_labelFloorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(cui_labelFloorTemp, "Floor");
    lv_obj_set_style_text_font(cui_labelFloorTemp, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_floorTempRoller;
    cui_floorTempRoller = lv_roller_create(cui_FloorSettingsComponent);
    lv_roller_set_options(cui_floorTempRoller, "1\n2\n3\n24", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(cui_floorTempRoller, 40);
    lv_obj_set_height(cui_floorTempRoller, 82);
    lv_obj_set_x(cui_floorTempRoller, -64);
    lv_obj_set_y(cui_floorTempRoller, -23);
    lv_obj_set_align(cui_floorTempRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_floorTempRoller, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(cui_floorTempRoller, lv_color_hex(0x149325), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_floorTempRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_floorTempRoller, &lv_font_montserrat_18, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_floorTempRoller, 6, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_floorTempRoller, lv_color_hex(0xCCEDD1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_floorTempRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_FLOORSETTINGSCOMPONENT_NUM);
    children[UI_COMP_FLOORSETTINGSCOMPONENT_FLOORSETTINGSCOMPONENT] = cui_FloorSettingsComponent;
    children[UI_COMP_FLOORSETTINGSCOMPONENT_LABELFLOORTEMP] = cui_labelFloorTemp;
    children[UI_COMP_FLOORSETTINGSCOMPONENT_FLOORTEMPROLLER] = cui_floorTempRoller;
    lv_obj_add_event_cb(cui_FloorSettingsComponent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_FloorSettingsComponent, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_FloorSettingsComponent_create_hook(cui_FloorSettingsComponent);
    return cui_FloorSettingsComponent;
}

