// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenHome_screen_init(void)
{
ui_ScreenHome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_ScreenHome, LV_DIR_TOP, 32);
lv_obj_set_width( ui_TabView1, lv_pct(100));
lv_obj_set_height( ui_TabView1, lv_pct(100));
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_tabhome = lv_tabview_add_tab(ui_TabView1, "Home");
lv_obj_set_flex_flow(ui_tabhome,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_tabhome, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

ui_homePumpStatusComponentFloor0 = ui_HomePumpStatusComponent_create(ui_tabhome);
lv_obj_set_x( ui_homePumpStatusComponentFloor0, 0 );
lv_obj_set_y( ui_homePumpStatusComponentFloor0, -10 );




ui_homePumpStatusComponentFloor1 = ui_HomePumpStatusComponent_create(ui_tabhome);
lv_obj_set_x( ui_homePumpStatusComponentFloor1, 0 );
lv_obj_set_y( ui_homePumpStatusComponentFloor1, -10 );




ui_tabsettings = lv_tabview_add_tab(ui_TabView1, "Settings");

ui_tabmanual = lv_tabview_add_tab(ui_TabView1, "WiFi");

lv_obj_add_event_cb(ui_homePumpStatusComponentFloor0, ui_event_homePumpStatusComponentFloor0_HomePumpStatusComponent, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_homePumpStatusComponentFloor1, ui_event_homePumpStatusComponentFloor1_HomePumpStatusComponent, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TabView1, ui_event_TabView1, LV_EVENT_ALL, NULL);

}
