// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, lv_pct(100));
lv_obj_set_height( ui_TabView1, lv_pct(100));
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_tabhome = lv_tabview_add_tab(ui_TabView1, "H");

ui_tabsettings = lv_tabview_add_tab(ui_TabView1, "Sett");

ui_tabmanual = lv_tabview_add_tab(ui_TabView1, "Man");


}
